### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by ghost** [kiyoaki/LineBot-Sample-for-DotNet#1]
Hi,

How can I make this app translate from language user types in to the language other user is using on mobile device or line?

Or if thats not possible how would I translate to more than one language?

**Comment by kiyoaki** [comment]
If your app know the other user's UserId, you can send to the user like this

https://github.com/kiyoaki/LineBot-Sample-for-DotNet/blob/master/LineTranslateBot/Functions.cs#L51

```csharp
await client.PushMessage({UserId}, translated);
```
But MessagingAPI's Push API is Developer Trial or Pro plan only.

https://at.line.me/jp/plan

![line-plan](https://user-images.githubusercontent.com/218958/38078871-93579f62-3378-11e8-81ff-d8349c8d548a.PNG)
